# Generated by Django 4.1.1 on 2022-10-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.IntegerField(verbose_name="Номер задачи")),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название задачи"),
                ),
                (
                    "task_text",
                    models.CharField(max_length=1000, verbose_name="Текст задачи"),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_input", models.CharField(max_length=255)),
                (
                    "expected_output",
                    models.CharField(max_length=255, verbose_name="Неправильный ввод"),
                ),
                (
                    "is_exception",
                    models.BooleanField(default=False, verbose_name="Ошибка"),
                ),
                (
                    "for_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labs.exercise",
                        verbose_name="К задаче",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="CompletedTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Labs.exercise",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполненая задача",
                "verbose_name_plural": "Выполненые задачи",
            },
        ),
    ]
