# Generated by Django 3.2.13 on 2022-12-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtasks",
            name="correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="expected_output",
            field=models.CharField(max_length=255, verbose_name="Ожидаемый ввод"),
        ),
    ]
